apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  mongo_uri: bW9uZ29kYitzcnY6Ly9zaGFzaGlkYXM6NDMxNzIxQGNsdXN0ZXIwLmV1dW14Lm1vbmdvZGIubmV0L3RvZG8tZGI/cmV0cnlXcml0ZXM9dHJ1ZSZhcHBOYW1lPUNsdXN0ZXIw
  jwt_secret: Y2RkNDE1ZTUzZDA2MjA0MzZjM2NkZGFlNDFmMDYwMWRmNjdkZDU4MjAwYzM2ZjhhZTAzNTJmMGY0YTY4YzYxMQ==
  gmail_username: c2hhc2hpZGFzOTVAZ21haWwuY29t
  gmail_password: dnhzeSB2aGxoIGtnZ2UgaGliZQ==

